title: GitHub Actions: "Using GitHub Script"
description: >-
  This course covers how to use GitHub Script to quickly use octokit/rest in a
  GitHub Actions workflow.
template:
  repo: write-github-script-template
  name: write-github-script
before:
  - type: createIssue
    title: Start here!
    body: 01_welcome-issue.md
    action_id: welcomeIssue
  - type: respond
    issue: "%actions.welcomeIssue.data.number%"
    with: 01_welcome-activity.md
    data:
      quicklink: "%payload.repository.html_url%/new/master?filename=.github/workflows/my-workflow.yml&workflow_template=blank"
      actionsUrl: "%payload.repository.html_url%/actions/new"

steps:
  - title: Setup a workflow file
    description: Create a pull request to add a workflow
    event: pull_request
    link: "{{ repoUrl }}/issues/%payload.pull_request.number%"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Create my-workflow.yml'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Create my-workflow.yml

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Create my-workflow.yml
          # if those gates === true Then do this stuff

      #######################################################
      # Validate the filepath for the my-workflow.yml file
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      # check for a file in a tree
      - type: gate
        left: "%actions.isInTree.data.tree%"
        operator: includes
        right: "path:.github/workflows/my-workflow.yml"
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: my-workflow.yml
            tree: "%actions.isInTree.data.tree%"
            # multiple: true
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            data:
              haveFile: "%actions.fileLocation.path%"
              needFile: ".github/actions/cat-facts/action.yml"
              editLink: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/%actions.fileLocation.path%"
              fileName: my-workflow.yml
        # End filepath verification
        #######################################################
      - type: respond
        issue: Start here!
        with: new-pull-request.md
        data:
          pullUrl: "%payload.pull_request.html_url%"
      - type: closeIssue
        issue: Start here!
      - type: respond
        with: 01_explain-workflow.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 02_modify-workflow.md
        issue: Create my-workflow.yml
        data:
          workflowFile: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/.github/workflows/my-workflow.yml"

  - title: Open an issue to trigger GitHub Script workflow
    description: Use GitHub script to comment when an issue is opened
    event: pull_request.synchronize
    link: "{{ repoUrl }}/issues/%payload.pull_request.number%"
    actions:
      #######################################################
      # Validate the filepath for the my-workflow.yml file
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      # check for a file in a tree
      - type: gate
        left: "%actions.isInTree.data.tree%"
        operator: includes
        right: "path:.github/workflows/my-workflow.yml"
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: my-workflow.yml
            tree: "%actions.isInTree.data.tree%"
            # multiple: true
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            data:
              haveFile: "%actions.fileLocation.path%"
              needFile: ".github/actions/cat-facts/action.yml"
              editLink: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/%actions.fileLocation.path%"
              fileName: my-workflow.yml
        # End filepath verification
        #######################################################
      - type: respond
        issue: Start here!
        with: 03_create-an-issue.md
        data:
          pullUrl: "%payload.pull_request.html_url%"
          actionsUrl: "%payload.repository.html_url%/actions"
          workflowFile: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/.github/workflows/my-workflow.yml"