title: "GitHub Actions: Using GitHub Script"
description: >-
  This course covers how to use GitHub Script to quickly use octokit/rest in a
  GitHub Actions workflow.
template:
  repo: write-github-script-template
  name: write-github-script
before:
  - type: updateBranchProtection
  - type: createProjectBoard
    name: Learning Lab Project Board
    description: >-
      This board is used with the GitHub Actions: Using GitHub Script Learning Lab course.
    columns:
      - Triage Backlog
      - Triage Complete

  - type: createIssue
    title: Start here!
    body: 00_welcome-issue.md
    store:
      welcomeIssueUrl: "%result.data.html_url%"
      welcomeIssueNumber: "%result.data.number%"
      createIssueResult: "%result%"
    data:
      quicklink: "%payload.repository.html_url%/new/master?filename=.github/workflows/my-workflow.yml"
      actionsUrl: "%payload.repository.html_url%/actions/new"
    comments:
      - 00_explain-gh-script.md
      - 00_octokit-comparison.md
      - 00_welcome-activity.md
      - e-result.md
  # - type: respond
  #   with: 00_explain-gh-script.md
  #   issue: "%actions.welcomeIssue.data.number%"
  # - type: respond
  #   with: 00_octokit-comparison.md
  #   issue: "%actions.welcomeIssue.data.number%"
  # - type: respond
  #   issue: "%actions.welcomeIssue.data.number%"
  #   with: 00_welcome-activity.md
  #   data:
  #     quicklink: "%payload.repository.html_url%/new/master?filename=.github/workflows/my-workflow.yml"
  #     actionsUrl: "%payload.repository.html_url%/actions/new"

steps:
  - title: Setup a workflow file
    description: Create a pull request to add a workflow
    event:
      - pull_request.opened
      - pull_request.edited
    link: "{{store.welcomeIssueUrl}}"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Create my-workflow.yml

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Create my-workflow.yml
          # if those gates === true Then do this stuff

      #######################################################
      # Validate the filepath for the my-workflow.yml file
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      # check for a file in a tree
      - type: gate
        left: "%actions.isInTree.data.tree%"
        operator: includes
        right: "path:.github/workflows/my-workflow.yml"
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: my-workflow.yml
            tree: "%actions.isInTree.data.tree%"
            # multiple: true
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            data:
              haveFile: "%actions.fileLocation.path%"
              needFile: ".github/workflows/my-workflow.yml"
              editLink: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/%actions.fileLocation.path%"
              fileName: my-workflow.yml
        # End filepath verification
        #######################################################
      - type: respond
        issue: "{{store.welcomeIssueNumber}}"
        with: new-pull-request.md
        data:
          pullUrl: "%payload.pull_request.html_url%"
      - type: closeIssue
        issue: "{{store.welcomeIssueNumber}}"
      - type: createReview
        body: 01_merge-workflow.md
        event: APPROVE
        store:
          firstPullUrl: "%result.data.html_url%"
          firstPullNumber: "%result.data.number%"
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Merge the new workflow into the master branch
    description: Make the workflow available for use on the repository
    event: pull_request.closed
    link: "{{store.firstPullUrl}}"
    actions:
      - type: createIssue
        title: Create an issue comment with GitHub Script
        body: 02_workflow-triggered.md
        action_id: triggerIssue
        store:
          secondIssueNumber: "%result.data.number%"
          secondIssueUrl: "%result.data.html_url%"
      - type: respond
        with: new-issue.md
        issue: "%store.firstPullNumber%"
        data:
          issueURL: "%store.firstPullUrl%"

  - title: Add another GitHub Script action
    description: Use GitHub Script to place this issue into a project board
    # event: check_suite.completed # issue_comment.created/edited
    event: issue_comment.created
    link: "{{store.secondIssueUrl}}"
    actions:
      - type: gate
        left: "%payload.check_suite.app.name%"
        operator: ===
        right: "GitHub Actions"
        else:
          - type: respond
            issue: "{{store.secondIssueNumber}}"
            with: debug.md
            data:
              debug: "%payload%"
      - type: respond
        with: 03_workflow-success.md
        issue: "{{store.secondIssueNumber}}"
      - type: octokit
        method: projects.listForRepo
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: projectBoard
      - type: octokit
        method: projects.listColumns
        project_id: "%actions.projectBoard.data.0.id%"
        action_id: listColumns
      - type: respond
        with: 03_add-to-projects.md
        issue: "{{store.secondIssueNumber}}"
        data:
          listProj: "%actions.projectBoard.data%"
          listCol: "%actions.listColumns.data%"
          columnID: "%actions.listColumns.data.0.id%"
          quicklink: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
    #  new pull request
  - title: Modify your workflow file
    description: Create a pull request to add changes to your workflow
    event:
      - pull_request.opened
      - pull_request.edited
    link: "{{ store.secondIssueUrl }}"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Update my-workflow.yml

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Update my-workflow.yml
          # if those gates === true Then do this stuff

      #######################################################
      # Validate the filepath for the my-workflow.yml file
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      # check for a file in a tree
      - type: gate
        left: "%actions.isInTree.data.tree%"
        operator: includes
        right: "path:.github/workflows/my-workflow.yml"
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: my-workflow.yml
            tree: "%actions.isInTree.data.tree%"
            # multiple: true
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            data:
              haveFile: "%actions.fileLocation.path%"
              needFile: ".github/actions/cat-facts/action.yml"
              editLink: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/%actions.fileLocation.path%"
              fileName: my-workflow.yml
        # End filepath verification
        #######################################################
      - type: respond
        issue: "{{store.secondIssueNumber}}"
        with: new-pull-request.md
        data:
          pullUrl: "%payload.pull_request.html_url%"
      - type: closeIssue
        issue: "{{store.secondIssueNumber}}"
      - type: createReview
        body: 04_merge-workflow.md
        event: APPROVE
        store:
          secondPullNumber: "%result.data.number%"
          secondPullUrl: "%result.data.html_url%"
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Merge the new workflow into the master branch
    description: Make the workflow available for use on the repository
    event: pull_request.closed
    link: "{{ store.secondPullUrl }}"
    actions:
      - type: createIssue
        title: Create an issue comment with GitHub Script
        body: 05_workflow-triggered.md
        action_id: triggerIssue
        store:
          thirdIssueUrl: "%result.data.html_url%"
          thirdIssueNumber: "%result.data.number%"
      - type: respond
        with: new-issue.md
        issue: "{{store.secondPullNumber}}"
        data:
          issueURL: "{{store.thirdIssueUrl}}"

  - title: Break your workflow into multiple steps
    description: Separate the workflow concerns by adding more steps
    # event: check_suite.completed
    event: issue_comment.created
    link: "{{store.thirdIssueUrl}}"
    actions:
      - type: gate
        left: "%payload.check_suite.app.name%"
        operator: ===
        right: "GitHub Actions"
        else:
          - type: respond
            issue: "{{store.thirdIssueNumber}}"
            with: debug.md
            data:
              debug: "%payload%"
      - type: octokit
        method: projects.listForRepo
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: projectBoard
      - type: octokit
        method: projects.listColumns
        project_id: "%actions.projectBoard.data.0.id%"
        action_id: listColumns
      - type: respond
        with: 06_steps-overview.md
        issue: "{{store.thirdIssueNumber}}"
        data:
          projectTab: "%payload.repository.html_url%/projects/1"
      - type: respond
        with: 06_steps-activity.md
        issue: "{{store.thirdIssueNumber}}"
        data:
          listProj: "%actions.projectBoard.data%"
          listCol: "%actions.listColumns.data%"
          columnID: "%actions.listColumns.data.0.id%"
          quicklink: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
          actionsTab: "%paylaod.repository.html_url%/actions"

  - title: Create better comments
    description: Use a templated repsonse as the comment body
    event: pull_request
    link: "{{repoUrl}}/pull/6"
    actions:
      - type: octokit
        method: projects.listForRepo
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: projectBoard
      - type: octokit
        method: projects.listColumns
        project_id: "%actions.projectBoard.data.0.id%"
        action_id: listColumns
      - type: respond
        issue: "{{store.thirdIssueNumber}}"
        with: new-pull-request.md
        data:
          pullUrl: "%payload.pull_request.html_url%"
      - type: closeIssue
        issue: "{{store.thirdIssueNumber}}"
      - type: respond
        with: 07_explain-node.md
      - type: respond
        with: 07_use-fs.md
        data:
          columnID: "%actions.listColumns.data.0.id%"
          quicklink: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/.github/workflows/my-workflow.yml"

  - title: Merge the final workflow
    description: Merge the final workflow into the repository
    event: pull_request.synchronize
    link: "{{repoUrl}}/pull/6"
    actions:
      - type: createReview
        body: 08_merge-workflow.md
        event: APPROVE

  - title: See workflow results
    description: See the results of the final workflow run
    event: pull_request.closed
    link: "{{repoUrl}}/issue/7"
    actions:
      - type: octokit
        action_id: triggerIssue
        method: issues.create
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        title: It's alive!
        body: |
          ## Great Job so far!  

          Like before, now we have to wait for the workflow to run so that we can see the results.  

          ---

          I'll respond here once it has completed!
        labels: ["bug"]

      - type: respond
        with: new-issue.md
        issue: 6
        data:
          issueURL: "%actions.triggerIssue.data.html_url%"

  - title: Open an issue
    description: Open another issue that does not contain the bug tag
    event: check_suite.completed
    link: "{{repoUrl}}/issue/7"
    actions:
      - type: respond
        with: 09_workflow-completed.md
        issue: 7
      - type: respond
        with: 09_issue-activity.md
        issue: 7
        data:
          quicklink: "%payload.repository.html_url%/issues/new"

  - title: Course recap
    description: Final notes on course
    event: check_suite.completed
    link: "{{repoUrl}}/issue/8"
    actions:
      - type: respond
        with: 10_workflow-completed.md
        issue: 8
      - type: respond
        with: 10_course-recap.md
        issue: 8
      - type: removeBranchProtection
